"""rosters

Revision ID: 0b6becfb7258
Revises: 0ce35ddead88
Create Date: 2026-09-23 03:50:31.821082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6becfb7258'
down_revision = '0ce35ddead88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('username_key', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('github_login', sa.String(length=39), nullable=False),
    sa.Column('github_user_id', sa.BigInteger(), nullable=True),
    sa.Column('github_status', sa.String(length=16), nullable=False),
    sa.Column('dropped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offering_id', 'username_key')
    )
    op.create_table('roster_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('base_revision', sa.Integer(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roster_revision', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.drop_column('roster_revision')

    op.drop_table('roster_uploads')
    op.drop_table('roster_entries')
    # ### end Alembic commands ###
