"""webhook deliveries

Revision ID: acf8f7243d30
Revises: 
Create Date: 2026-09-22 22:30:25.095688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf8f7243d30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_deliveries')
    # ### end Alembic commands ###
