"""org membership

Revision ID: cc2d374458ae
Revises: 0b6becfb7258
Create Date: 2026-09-23 04:07:08.665082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2d374458ae'
down_revision = '0b6becfb7258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invites_resume_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('memberships_checked_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('roster_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership', sa.String(length=16), server_default='unknown', nullable=False))
        batch_op.add_column(sa.Column('membership_error', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster_entries', schema=None) as batch_op:
        batch_op.drop_column('checked_at')
        batch_op.drop_column('invited_at')
        batch_op.drop_column('membership_error')
        batch_op.drop_column('membership')

    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.drop_column('memberships_checked_at')
        batch_op.drop_column('invites_resume_at')

    # ### end Alembic commands ###
