#!/usr/bin/env node
/*
 * test.js, cs108 a01: Hello, graded in JavaScript
 *
 * Run with:  npm test        (or:  node test.js)
 *
 * This is the VISIBLE suite. It ships in the starter repository, students run
 * it as often as they like, and the grader runs this exact file (restored
 * from the instructor's copy) to produce the mark. There is nothing to
 * install: it uses only node:assert, which is part of Node itself, because
 * the runners that give the green tick have no network and `npm install`
 * there would fail.
 *
 * DO NOT EDIT THIS FILE. It is on the assignment's restore list, so grading
 * overwrites it with the instructor's copy anyway; edits here change what you
 * see locally and nothing else.
 *
 * HOW A CHECK IS WRITTEN (for the instructor)
 *
 *     check("Step 1: add(2, 3) is 5", () => {
 *       assert.equal(app.add(2, 3), 5,
 *         "add should return the sum of its two arguments");
 *     });
 *
 *   The third argument of an assertion is the HINT the student sees when it
 *   fails. Write the hint as the thing you would say leaning over their
 *   shoulder. It is the part of the assignment that teaches; treat writing
 *   good hints as writing the assignment, not as decoration.
 *
 *   A check function may also return an array of hint strings (empty means
 *   pass), or return a Promise for asynchronous code. Throwing anything
 *   counts as a failure with the error's message as the hint.
 *
 * OUTPUT FORMAT (do not change; the workflow and the grader parse it)
 *
 *     PASS  Step 1: add(2, 3) is 5
 *     FAIL  Step 2: empty input
 *           Hint: an empty file should produce an empty array, not throw
 *     Results: 2 / 3 passed
 *
 *   When COURSE_JSON_OUT names a file, every check is also recorded there as
 *   JSON so the grader can award per-check credit. It is unset when a student
 *   runs `npm test`, so it costs them nothing.
 */

"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

// ── the tiny runner ──────────────────────────────────────────────────────

const JSON_OUT = process.env.COURSE_JSON_OUT || "";
const results = [];             // {name, passed, hints}
const queue = [];               // checks run in the order they were declared
const color = process.stdout.isTTY && !process.env.NO_COLOR;
const paint = (code, s) => (color ? `\x1b[${code}m${s}\x1b[0m` : s);

/** Declare one check. `fn` may be sync or async, may return hints or throw. */
function check(label, fn) {
  queue.push({ label, fn });
}

/**
 * Load a student module without letting a crash take the whole suite down.
 * A file that fails to load is reported as a build failure: every check is
 * then scored zero out of the full total, which keeps the denominator stable.
 */
function load(relativePath) {
  try {
    return require(path.resolve(process.cwd(), relativePath));
  } catch (err) {
    const message = `${relativePath} could not be loaded: ${err && err.message ? err.message : err}`;
    console.log(paint(31, "Build failed.") + " " + message);
    console.log("Fix the error above, then run `npm test` again.\n");
    emit(false, message);
    process.exit(1);
  }
}

function emit(buildOk, buildError) {
  if (!JSON_OUT) return;
  fs.writeFileSync(JSON_OUT, JSON.stringify(
    { build: buildOk, build_error: buildError || "", tests: results }, null, 2));
}

async function runOne({ label, fn }) {
  let hints = [];
  try {
    const out = await fn();
    if (Array.isArray(out)) hints = out.map(String);
  } catch (err) {
    hints = [err && err.message ? String(err.message).split("\n")[0] : String(err)];
  }
  const passed = hints.length === 0;
  results.push({ name: label, passed, hints });
  if (passed) {
    console.log(`  ${paint(32, "PASS")}  ${label}`);
  } else {
    console.log(`  ${paint(31, "FAIL")}  ${label}`);
    for (const h of hints) console.log(`         ${paint(33, "Hint:")} ${h}`);
  }
}

async function main() {
  for (const item of queue) await runOne(item);
  const passed = results.filter((r) => r.passed).length;
  console.log(`\nResults: ${passed} / ${results.length} passed`);
  emit(true, "");
  process.exit(passed === results.length ? 0 : 1);
}

// ── the checks ───────────────────────────────────────────────────────────
// Everything below this line is the assignment. Everything above is the
// runner, identical in every assignment; copy it, do not rewrite it.

const app = load("./app.js");

check("Step 1: add(2, 3) is 5", () => {
  assert.equal(app.add(2, 3), 5, "add should return the sum of its two arguments");
});

check("Step 1: add works with negative numbers", () => {
  assert.equal(app.add(-4, 1), -3, "add(-4, 1) should be -3; check the sign");
});

check("Step 2: greet('Ada') says hello by name", () => {
  assert.equal(app.greet("Ada"), "Hello, Ada!",
    "greet should return exactly `Hello, <name>!` with a comma and an exclamation mark");
});

check("Step 2: greet with no name greets the world", () => {
  assert.equal(app.greet(), "Hello, world!",
    "when no name is given, greet should fall back to `world`");
});

main();
